### ISSUE TITLE
Getting 'Unknown Kotlin JVM target: 21' error if we build with JDK 21.

### ISSUE THREAD

**Issue by rajurevoori** [talsec/Free-RASP-Capacitor#21]
### Description
In new Android Studio(Ladybug | 2024.2.1 Patch 1 which released on Build #AI-242.23339.11.2421.12483815, built on October 11, 2024) default android gradle JDK version set to 21. When we add this plugin and try to run the app getting below error.

org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':capacitor-freerasp:compileDebugKotlin'.
Caused by: java.lang.IllegalArgumentException: Unknown Kotlin JVM target: 21

### To Reproduce
Add this plugin to ionic capacitor project.
Update gradle JDK to 21
Build the app.
Expected behavior
We should not get any kotlin compatable error with JDK 21

### Please complete the following information:
Build issue.
Version of freeRASP:1.4.0, 1.5.2

### Additional context
At least add below kotlin options in the plugin gradle.
kotlinOptions { jvmTarget = "17" }

**Comment by msikyna** [comment]
Hello @rajurevoori ,
we will look at the issue, thank you for reporting it.

Kind regards,
Talsec team

**Comment by rajurevoori** [comment]
@msikyna , When are you planning to release this fix?

**Comment by tompsota** [comment]
Hi @rajurevoori,

adding kotlinOptions { jvmTarget = "17" } as you suggested fixes the problem. We'll add this into the next release, which should be out at latest next week.

To compile the project now, you can either set JDK to 17 in Android Studio, or add kotlinOptions in the build.gradle in our plugin (_node_modules/capacitor-freerasp/android/build.gradle_)

Regards,
Tomas from Talsec

**Comment by mps-pso** [comment]
Will this be going out with release 1.6.0? Also having the same issues.

**Comment by tompsota** [comment]
@mps-pso,

Yes, it will

Regards,
Tomas from Talsec

**Comment by mps-pso** [comment]
> @mps-pso,
> 
> Yes, it will
> 
> Regards, Tomas from Talsec

Thank you, I suspected as much. I did the manual change in the grade as suggested but always feel uneasy changing package files.

**Comment by rajurevoori** [comment]
Thank you all for fix.
